- amount_generations: 50
  fitness_selection: 5
  generation_size: 15
  good_enough_number: 2
  mutation_factor: 1
  num_runs: 10
  stagnation_threshold: 1
- amount_generations: 50
  fitness_selection: 5
  generation_size: 15
  good_enough_number: 1
  mutation_factor: 1
  num_runs: 10
  stagnation_threshold: 1
- amount_generations: 50
  fitness_selection: 5
  generation_size: 15
  good_enough_number: 1
  mutation_factor: 1
  num_runs: 10
  stagnation_threshold: 1
